---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: Set system hostname
  ansible.builtin.include_tasks: 'hostname.yml'

- name: Set sysctl entries
  ansible.builtin.include_tasks: 'sysctl.yml'
