---
- name: persistent hostname is set
  copy:
    dest: /etc/myname
    owner: "{{ system_root_user }}"
    group: "{{ system_root_group }}"
    mode: "0644"
    content: "{{ system_hostname }}"
  notify: update hostname

- name: persistent sysctls are set
  sysctl:
    name: "{{ setting.key }}"
    value: "{{ setting.value }}"
    sysctl_file: "{{ system_sysctl_config_file }}"
    sysctl_set: true
  loop:
    "{{ system_sysctl_config | default({}, True) | dict2items }}"
  loop_control:
    loop_var: setting
  when:
    - system_sysctl_config is defined

- block:
    - name: persistent kernel config is set
      template:
        src: "openbsd/kernel.conf/kernel.conf.j2"
        dest: "{{ system_kernel_config_file }}"
        owner: "{{ system_root_user }}"
        group: "{{ system_root_group }}"
        mode: "0640"
    - name: Shutdown script exists
      file:
        state: touch
        path: "/etc/rc.shutdown"
        access_time: preserve
        modification_time: preserve
        owner: "{{ system_root_user }}"
        group: "{{ system_root_group }}"
        mode: "0644"
    - name: KARL@next-boot is enabled for persistent custom kernel config
      blockinfile:
        path: "/etc/rc.shutdown"
        block: "{{ lookup('template', 'templates/openbsd/kernel.conf/rc.shutdown.j2') }}"
        marker: "# {mark} KARL@next-boot for customized kernel"
  when:
    - system_kernel_config is defined
    - system_kernel_config | length > 0

- name: e-mail for root is forwarded
  lineinfile:
    line: "{{ system_mgmt_reports.email }}"
    regexp: "{{ system_mgmt_reports.email }}"
    state: present
    path: "{{ system_root_home }}/.forward"
    owner: "{{ system_root_user }}"
    group: "{{ system_root_group }}"
    mode: "0640"
  when:
    - system_mgmt_reports.email is defined
    - system_mgmt_reports.email

- name: cron job for syspatch(8) update check
  cron:
    name: Check for available syspatch(8) updates
    hour: "2"
    minute: "~"
    job: >
      syspatch -c
  when:
    - system_cron_update
