---
name: CI/CD
on:
  pull_request:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install linting dependencies
        run: pip3 install yamllint ansible-base ansible-lint

      - name: Create ansible.cfg for testing
        run: |
          cat <<EOF > ansible.cfg
          [defaults]
          inventory = inventory
          EOF

      - name: Create inventory for testing
        run: |
          cat <<EOF > inventory
          [all]
          localhost ansible_host=127.0.0.1
          EOF

      - name: Lint code
        run: |
          yamllint .
          ansible-lint
